name: wol-repeater
services:
    wol-repeater:
        image: wol-repeater
        network_mode: host
        environment:
            - ENV_ADDR=192.168.1.100
            - ENV_BROADCAST=192.168.1.255
            - ENV_PORT=9
